#!/bin/bash
controllerMAC=<MAC OF CONTROLLER>
anyConnect=$(hcitool con | grep "$controllerMAC" | grep "state 1" | wc -l)

counter=1

#try to connect to any controller if none are connected
#longest this will run is 55 seconds
while [ $anyConnect -eq 0 ] && [ $counter -lt 11 ]
do
 bluetoothctl -- connect $controllerMAC
 sleep  5

 ((counter++))
 anyConnect=$(hcitool con | grep "$controllerMAC" | grep "state 1" | wc -l)
done

